type = "checkout_ui"
name = "resident-id"

extension_points = [
  'Checkout::Dynamic::Render'
]

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"
